name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout SerenityOS
        uses: actions/checkout@v2
        with:
          repository: SerenityOS/serenity
          path: serenity

      - name: Install prerequisites
        run: sudo apt install -y build-essential cmake ninja-build libmpfr-dev libmpc-dev libgmp-dev e2fsprogs curl

      - name: Build Toolchain
        working-directory: serenity/Toolchain
        run: ./BuildIt.sh

      - name: Generate build files
        working-directory: serenity/Build
        run: cmake .. -G Ninja

      - name: Build SerenityOS
        working-directory: serenity/Build
        run: ninja -j$((nprocs + 1))

      - name: Install SerenityOS
        working-directory: serenity/Build
        run: ninja install
