name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout SerenityOS
        uses: actions/checkout@v2
        with:
          repository: SerenityOS/serenity
          path: serenity

      - name: Install prerequisites
        run: sudo apt install -y build-essential cmake ninja-build libmpfr-dev libmpc-dev libgmp-dev e2fsprogs curl

      - name: Install GCC
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 900 --slave /usr/bin/g++ g++ /usr/bin/g++-10

      - name: Check GCC version
        run: gcc --version

      - name: Cache Toolchain
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/Toolchain/Cache/
          # Keep in sync with SerenityOS' workflow.
          key: ${{ runner.os }}-toolchain-i686-${{ hashFiles('Userland/Libraries/LibC/**/*.h', 'Toolchain/Patches/*.patch', 'Toolchain/BuildIt.sh') }}

      - name: Build Toolchain
        working-directory: ${{ github.workspace }}/serenity/Toolchain/
        run: TRY_USE_LOCAL_TOOLCHAIN=y ./BuildIt.sh

      - name: Generate build files
        working-directory: ${{ github.workspace }}/serenity/Build/
        run: cmake ${{ github.workspace }}/serenity -G Ninja

      - name: Build SerenityOS
        working-directory: ${{ github.workspace }}/serenity/Build/
        run: ninja -j$((nprocs + 1))

      - name: Install SerenityOS
        working-directory: ${{ github.workspace }}/serenity/Build/
        run: ninja install
