name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00

env:
  SERENITY_ROOT: ${{ github.workspace }}/serenity
  BUILD_ROOT: ${{ env.SERENITY_ROOT }}/Build

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout SerenityOS
        uses: actions/checkout@v2
        with:
          repository: SerenityOS/serenity
          path: ${{ env.SERENITY_ROOT }}

      - name: Update APT cache
        run: sudo apt update -y

      - name: Install script dependencies
        run: |
          sudo apt install -y curl python3-pip
          pip3 install --user requests

      - name: Install SerenityOS prerequisites
        run: sudo apt install -y build-essential cmake ninja-build libmpfr-dev libmpc-dev libgmp-dev e2fsprogs curl qemu-system-i386 qemu-utils

      - name: Set environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 ${{ github.workspace }}/scripts/env.py

      - name: Set up GCC 10
        run: |
          sudo apt install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 900 --slave /usr/bin/g++ g++ /usr/bin/g++-10
          gcc --version && g++ --version

      - name: Cache Toolchain
        uses: actions/cache@v2
        with:
          path: ${{ env.SERENITY_ROOT }}/Toolchain/Cache/
          # Keep in sync with SerenityOS' workflow.
          key: ${{ runner.os }}-toolchain-i686-${{ hashFiles('serenity/Userland/Libraries/LibC/**/*.h', 'serenity/Toolchain/Patches/*.patch', 'serenity/Toolchain/BuildIt.sh') }}

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: setup

    steps:
      - name: Build Toolchain
        working-directory: ${{ env.SERENITY_ROOT }}/Toolchain/
        run: TRY_USE_LOCAL_TOOLCHAIN=y ./BuildIt.sh

      - name: Create the Build directory
        working-directory: ${{ env.SERENITY_ROOT }}
        run: mkdir -pv ${{ env.BUILD_ROOT }}

      - name: Build & Install SerenityOS
        working-directory: ${{ env.BUILD_ROOT }}
        run: |
          cmake ${{ env.SERENITY_ROOT }} -G Ninja
          ninja -v
          ninja -v install

      - name: Generate GRUB image
        working-directory: ${{ env.BUILD_ROOT }}
        run: |
          ninja grub-image
          cp -v ${{ env.BUILD_ROOT }}/grub_disk_image ${{ env.BUILD_ROOT }}/serenity-grub-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.img

      - name: Generate VirtualBox Disk Image
        working-directory: ${{ env.BUILD_ROOT }}
        run: |
          qemu-img convert -O vdi ${{ env.BUILD_ROOT }}/grub_disk_image ${{ env.BUILD_ROOT }}/serenity-virtualbox-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.vdi

      - name: Generate VMWare Disk Image
        working-directory: ${{ env.BUILD_ROOT }}
        run: |
          qemu-img convert -O vmdk ${{ env.BUILD_ROOT }}/grub_disk_image ${{ env.BUILD_ROOT }}/serenity-vmware-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.vmdk

  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}
          release_name: SerenityOS Daily ${{ env.SERENITY_DAILY_DATE }} Build ${{ env.SERENITY_DAILY_BUILD }} Commit ${{ env.SERENITY_DAILY_COMMIT }}

      - name: Upload GRUB image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUILD_ROOT }}/serenity-grub-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.img
          asset_name: serenity-grub-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.img
          asset_content_type: application/octet-stream

      - name: Upload VirtualBox Disk Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUILD_ROOT }}/serenity-virtualbox-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.vdi
          asset_name: serenity-virtualbox-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.vdi
          asset_content_type: application/octet-stream

      - name: Upload VMWare Disk Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUILD_ROOT }}/serenity-vmware-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.vmdk
          asset_name: serenity-vmware-${{ env.SERENITY_DAILY_DATE }}-${{ env.SERENITY_DAILY_BUILD }}-${{ env.SERENITY_DAILY_COMMIT }}.vmdk
          asset_content_type: application/octet-stream
