name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 12 * * *" # Every day at 12:00

env:
  SERENITY_ROOT: ${{ github.workspace }}/serenity

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout SerenityOS
        uses: actions/checkout@v2
        with:
          repository: SerenityOS/serenity
          path: serenity

      - name: Install prerequisites
        run: sudo apt install -y build-essential cmake ninja-build libmpfr-dev libmpc-dev libgmp-dev e2fsprogs curl qemu-system-i386 qemu-utils

      - name: Install GCC
        run: |
          sudo apt install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 900 --slave /usr/bin/g++ g++ /usr/bin/g++-10

      - name: Check GCC version
        run: gcc --version

      - name: Cache Toolchain
        uses: actions/cache@v2
        with:
          path: ${{ env.SERENITY_ROOT }}/Toolchain/Cache/
          # Keep in sync with SerenityOS' workflow.
          key: ${{ runner.os }}-toolchain-i686-${{ hashFiles('serenity/Userland/Libraries/LibC/**/*.h', 'serenity/Toolchain/Patches/*.patch', 'serenity/Toolchain/BuildIt.sh') }}

      - name: Build Toolchain
        working-directory: ${{ env.SERENITY_ROOT }}/Toolchain/
        run: TRY_USE_LOCAL_TOOLCHAIN=y ./BuildIt.sh

      - name: Create the Build directory
        working-directory: ${{ env.SERENITY_ROOT }}
        run: mkdir -pv ${{ env.SERENITY_ROOT }}/Build/

      - name: Generate build files
        working-directory: ${{ env.SERENITY_ROOT }}/Build/
        run: cmake -v ${{ env.SERENITY_ROOT }}/ -G Ninja

      - name: Build SerenityOS
        working-directory: ${{ env.SERENITY_ROOT }}/Build/
        run: ninja -v -j$((nprocs + 1))

      - name: Install SerenityOS
        working-directory: ${{ env.SERENITY_ROOT }}/Build/
        run: ninja -v install

      - name: Build QEMU Image
        working-directory: ${{ env.SERENITY_ROOT }}/Build/
        run: ninja -v qemu-image

      - name: Build GRUB Image
        working-directory: ${{ env.SERENITY_ROOT }}/Build/
        run: ninja -v grub-image

      - name: Set release variables
        run: |
          echo "SERENITYOS_DAILY_DATE=$(date +%y%m%d)" >> $GITHUB_ENV
          echo "SERENITYOS_DAILY_DATE_PRETTY=$(date +%Y/%m/%d)" >> $GITHUB_ENV
          # Update the PATCH file everytime we need a new build.
          echo "SERENITYOS_DAILY_PATCH=$(cat ${{ github.workspace }}/PATCH)" >> $GITHUB_ENV

      - id: create_release
        name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.SERENITYOS_DAILY_DATE }}.${{ env.SERENITYOS_DAILY_PATCH }}
          release_name: SerenityOS Daily (${{ env.SERENITYOS_DAILY_DATE_PRETTY }} Patch ${{ env.SERENITYOS_DAILY_PATCH }})

      - name: Update QEMU Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.SERENITY_ROOT }}/Build/_disk_image
          asset_name: serenity-qemu-${{ env.SERENITYOS_DAILY_DATE }}.${{ env.SERENITYOS_DAILY_PATCH }}.img
          asset_content_type: application/octet-stream

      - name: Update GRUB Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.SERENITY_ROOT }}/Build/grub_disk_image
          asset_name: serenity-grub-${{ env.SERENITYOS_DAILY_DATE }}.${{ env.SERENITYOS_DAILY_PATCH }}.img
          asset_content_type: application/octet-stream
